name: API CI

on:
  push:
    branches: [ gitActions ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest   # se quiser pode usar o windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cypress run (CI + Mochawesome)
        uses: cypress-io/github-action@v6
        with:
          install-command: npm install
          command: npm run cy:run-ci
        continue-on-error: true   # se quiser que quebre o pipeline quando falhar, troque para false ou remova

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
          publish_branch: gh-pages   # se o curso pedir publicação em gh-pages
